---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
# networking:
#   podSubnet: 10.244.0.0/16,2001:db8:42:0::/56
#   serviceSubnet: 10.96.0.0/16,2001:db8:42:1::/112
clusterName: "the-office"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
skipPhases:
  - addon/kube-proxy
