apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      version: 1.13.x
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: -1 # keep trying to remediate
    crds: CreateReplace # Upgrade CRDs on package update
  releaseName: rook-ceph-cluster
  values:
    cephClusterSpec:
      dashboard:
        ssl: false
      crashCollector:
        disable: true
      resources:
        mgr:
          limits:
            cpu: "400m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
        mon:
          limits:
            cpu: "400m"
            memory: "256Mi"
          requests:
            cpu: "200"
            memory: "128Mi"
        osd:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        mgr-sidecar:
          limits:
            cpu: "100m"
            memory: "100Mi"
          requests:
            cpu: "50m"
            memory: "40Mi"
        logcollector:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        cleanup:
          limits:
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "50Mi"
      removeOSDsIfOutAndSafeToRemove: true
    ingress:
      dashboard:
        {}
        # annotations:
        #   external-dns.alpha.kubernetes.io/hostname: dashboard.example.com
        #   nginx.ingress.kubernetes.io/rewrite-target: /ceph-dashboard/$2
        # If the dashboard has ssl: true the following will make sure the NGINX Ingress controller can expose the dashboard correctly
        #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        #   nginx.ingress.kubernetes.io/server-snippet: |
        #     proxy_ssl_verify off;
        # host:
        #   name: dashboard.example.com
        #   path: "/ceph-dashboard(/|$)(.*)"
        # tls:
        # - hosts:
        #     - dashboard.example.com
        #   secretName: testsecret-tls
        ## Note: Only one of ingress class annotation or the `ingressClassName:` can be used at a time
        ## to set the ingress class
        # ingressClassName: nginx

    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              limits:
                cpu: "200m"
                memory: "512m"
              requests:
                cpu: "100m"
                memory: "256m"
            priorityClassName: system-cluster-critical

    cephObjectStores: []
