---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard.vanstraten.cloud
  namespace: personal
spec:
  secretName: wildcard.vanstraten.cloud
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: "*.vanstraten.cloud"
  dnsNames:
    - "vanstraten.cloud"
    - "*.vanstraten.cloud"
