---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: ">=26.0"
  interval: 1h
  values:
    deployment:
      enabled: true
      kind: Deployment
      replicas: 1
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: false
    ports:
      web:
        redirectTo:
          port: websecure
    service:
      externalIPs:
        - 152.53.16.168
        - 92.60.39.158
        - 152.53.17.249
