---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBZAKjaS+Zf7v2wKo0eKB35Gll+F4PgZR1Vf/pscC47AVxNhyDNgrmgrQugifqVIOVuGNFv2RH2Zgf/NDR1mxjDIEPctFDfW0Y5Uop2K/Y/l3Oxi4Bh8nwjQ3G77dxes5BVmfrTnw257ronTpf9//z2jGqO3T1bo8Chjx5Y9aVsv5H16CUaa0ZgUclDsM/06Rhxp+59QVDXGX+AHHxbcwzVLYqudFU5LrfUrbPeN3CN2TJnCS+9v94w56FizvAdwp8rM1tT8O3+qwCOVfbAJorByH13TGIWADG6a/FrW6xbh3J/L33fgBzxQmhDVdeWqYcY7HM3qYihYQCz9weyQSBe+tKYy/2CuRU7gJwkNf3TW7YiW8oNHBd9UDtCfxeZPpI9ufTJVk2Ph41FUBKvRcFVqqOaNTR/wOAidBzjqb79VbUqXnvMTKinRb80cFLFj9IEjlIXZQQ1YQmc4EpC7LHnb/B3O+Wh7XnyYucv4ObDPYzgBvxS3qy0xCaZz/pPa445QqR7LwPvvIackeksTe+MHQXwc0m7FrqU+Y0ExXb2lfrm5IJO9K16b6sWOt/oNaW51CjzPXHhShvYTLLdprYP+z+aabgjyGjQ+E7H7PF4QRjNeX6OKcfM/rcP9t7dax8FGtp5T9NdJkA+Nz/yg4ddb21175UoKoHaXqi9//tdOivqLNCTeJUE0GBZ0XlwwfmFh1MFH8y2whdrl5hFWBihq2GTTlX7B8RmE45YkrcNPJaIOmYjAITC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
