---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: personal
spec:
  interval: 5m
  path: "./personal/certificates"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: false
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: wildcard.vanstraten.cloud
      namespace: personal
  dependsOn:
    - name: cluster-issuers
      namespace: cert-manager
