---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: ">=2.14.0"
  install:
    crds: Create
  interval: 1h
  releaseName: sealed-secrets-controller
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace
