---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api 
  namespace: kube-system
spec:
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    branch: release-1.0
  interval: 48h
---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: kube-system
spec:
  interval: 5m
  path: ./config/crd/experimental
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api
