---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitea
  namespace: personal
spec:
  chart:
    spec:
      chart: gitea
      version: 10.x
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
  interval: 20m
  values:
    gitea:
      admin:
        existingSecret: gitea-admin-secret
      config:
        repository:
          DISABLE_HTTP_GIT: true
        server:
          DOMAIN: gitea.vanstraten.cloud
          ROOT_URL: https://gitea.vanstraten.cloud/
        security:
          PASSWORD_HASH_ALGO: bcrypt
        service:
          DISABLE_REGISTRATION: true
    ingress:
      enabled: true
      hosts:
        - host: gitea.vanstraten.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "gitea.vanstraten.cloud"
          secretName: wildcard.vanstraten.cloud
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.domains.0.main: "vanstraten.cloud"
        traefik.ingress.kubernetes.io/router.tls.domains.0.sans: "*.vanstraten.cloud"
    persistence:
      enabled: true
      storageClass: rook-cephfs
      accessModes:
        - ReadWriteMany
    service:
      ssh:
        type: LoadBalancer
        externalIPs:
          - 152.53.16.168
          - 92.60.39.158
          - 152.53.17.249
