---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitea
  namespace: personal
spec:
  chart:
    spec:
      chart: gitea
      version: 10.x
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
  interval: 20m
  values:
    gitea:
      admin:
        existingSecret: gitea-admin-secret
      config:
        repository:
          DISABLE_HTTP_GIT: true
          ENABLE_PUSH_CREATE_USER: true
          ENABLE_PUSH_CREATE_ORG: true
        ui:
          THEMES: auto,gitea,arc-green,catppuccin-latte-rosewater,catppuccin-latte-flamingo,catppuccin-latte-pink,catppuccin-latte-mauve,catppuccin-latte-red,catppuccin-latte-maroon,catppuccin-latte-peach,catppuccin-latte-yellow,catppuccin-latte-green,catppuccin-latte-teal,catppuccin-latte-sky,catppuccin-latte-sapphire,catppuccin-latte-blue,catppuccin-latte-lavender,catppuccin-frappe-rosewater,catppuccin-frappe-flamingo,catppuccin-frappe-pink,catppuccin-frappe-mauve,catppuccin-frappe-red,catppuccin-frappe-maroon,catppuccin-frappe-peach,catppuccin-frappe-yellow,catppuccin-frappe-green,catppuccin-frappe-teal,catppuccin-frappe-sky,catppuccin-frappe-sapphire,catppuccin-frappe-blue,catppuccin-frappe-lavender,catppuccin-macchiato-rosewater,catppuccin-macchiato-flamingo,catppuccin-macchiato-pink,catppuccin-macchiato-mauve,catppuccin-macchiato-red,catppuccin-macchiato-maroon,catppuccin-macchiato-peach,catppuccin-macchiato-yellow,catppuccin-macchiato-green,catppuccin-macchiato-teal,catppuccin-macchiato-sky,catppuccin-macchiato-sapphire,catppuccin-macchiato-blue,catppuccin-macchiato-lavender,catppuccin-mocha-rosewater,catppuccin-mocha-flamingo,catppuccin-mocha-pink,catppuccin-mocha-mauve,catppuccin-mocha-red,catppuccin-mocha-maroon,catppuccin-mocha-peach,catppuccin-mocha-yellow,catppuccin-mocha-green,catppuccin-mocha-teal,catppuccin-mocha-sky,catppuccin-mocha-sapphire,catppuccin-mocha-blue,catppuccin-mocha-lavender
        server:
          DOMAIN: gitea.vanstraten.cloud
          ROOT_URL: https://gitea.vanstraten.cloud/
        security:
          PASSWORD_HASH_ALGO: bcrypt
        service:
          DISABLE_REGISTRATION: true
    ingress:
      enabled: true
      hosts:
        - host: gitea.vanstraten.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "gitea.vanstraten.cloud"
          secretName: wildcard.vanstraten.cloud
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.domains.0.main: "vanstraten.cloud"
        traefik.ingress.kubernetes.io/router.tls.domains.0.sans: "*.vanstraten.cloud"
    persistence:
      enabled: true
      storageClass: rook-cephfs
      accessModes:
        - ReadWriteMany
    service:
      ssh:
        type: LoadBalancer
        externalIPs:
          - 152.53.16.168
          - 92.60.39.158
          - 152.53.17.249
