---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea
  namespace: personal
spec:
  interval: 5m
  path: "./personal/gitea/chart"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  # dependsOn:
  #   - name: cilium
  #     namespace: kube-system
