---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBNjeHQDXa8jkUNuhcoTpM3TJhXQU+52gBD8vUwGy2G5/ibSL+1IKnEE9bN/fXOICyB+ghDZyJNGA9cGsrBy6NWqvj6ij+KrIFCLJqlwn34LuLdCV3YHm+dqL7Rp/Cd4/eTicQubcyiXRl2zFbtG1DseVYy9wD45PT7/CktV41RnoLcbK9tDeb3FnnCWVx1THKL90eYpvgTK6UYThs+mh5tNcKCu69kYeTkfdK7zrp6J4O3ypLQwn05nUlM+Js6rddMKB5Y//gAtn+ROZGsi5Y4GvbrYMRjRctwMfXiI2hQCRshN3hX7gxHcWY/s6tXVbcY8GfdSRAZ4+W/wCraMSV3587HwQBKEXrNz9GrBhVcf1dTjR9zzA6wrQE8CpiwQyDC1MoINbI1h65ib9bIArnfg2YK+w3XER+MMd2H4i32wBlc0b11VF9PmBqbW/qC2vN+TLXAHGPJC+3wVKcO+7jgLgewRl84bUpXxXoC39e3wvFQ+jOQeTga/5ArayZp3dQdOc96x6es3FlXzbcIh2GLIPHEVbgkFxlZLHY5uY+XupsmKpzPt7OMrh1Uf6gB41ku8kNCHLTrp4eC8WuQfjTVigbsly2xjOw3OV0PCQlLXWC054OVjmmvzEJYBXLO9ELSFnlm24wgh/WTAj7fFd/m4i0Hhi3pMDGmDazEg1ztvZGWF7tk8SREKnLGz1fAM94zSUuOE5iH1M9BIvn+/otJx7SFn1jqoEiIpIsGrbz7gA+CbXZ/jieC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
